/*
 * Globalize Culture ja-JP
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "ko-KR", "default", {
	name: "ko-KR",
	englishName: "Korean (Korea)",
	nativeName: "한국어(한국)",
	language: "ko",
	calendars: {
		standard: {
			days: {
				names: ["일","월","화","수","목","금","토"],
				namesAbbr: ["일","월","화","수","목","금","토"],
				namesShort: ["일","월","화","수","목","금","토"]
			},
			months: {
				names: ["1월","2월","3월","4월","5월","6월","7월","8월","9월","10월","11월","12월",""],
				namesAbbr: ["1","2","3","4","5","6","7","8","9","10","11","12",""]
			},
			AM: ["오전","오전","오전"],
			PM: ["오전","오전","오전"],
			eras: [{ "name": "A.D.", "start": null, "offset": 0 }],
			patterns: {
				d: "yyyy-MM-dd",
				D: "yyyy'년'M'월'd'일'",
				t: "H:mm",
				T: "H:mm:ss",
				f: "yyyy'년'M'월'd'일' H:mm",
				F: "yyyy'년'M'월'd'일' H:mm:ss",
				M: "M'월'd'일'",
				Y: "yyyy'년'M'월'"
			}
		}
	}
});

}( this ));
